export enum Kind {
  // Models
  Namespace = "Namespace",
  Import = "Import",
  Alias = "Alias",
  Interface = "Interface",
  Role = "Role",
  Operation = "Operation",
  Parameter = "Parameter",
  Type = "Type",
  Field = "Field",
  Union = "Union",
  Enum = "Enum",
  EnumValue = "EnumValue",
  Directive = "Directive",
  Require = "Require",
  Annotation = "Annotation",
  Argument = "Argument",
  Void = "Void",
  Primitive = "Primitive",
  List = "List",
  Map = "Map",
  Optional = "Optional",
  Stream = "Stream",
}
