name: Build

on:
  push:
    branches:
      - main
      - release-*
    tags:
      - v*
  pull_request:
    branches:
      - main
      - release-*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/

      - name: Bundle module and dependencies
        run: deno run -A scripts/build_npm.ts ${GITHUB_REF##*/}

      - name: Is Release?
        if: startswith(github.ref, 'refs/tags/v')
        run: echo "DEPLOY_PACKAGE=true" >> $GITHUB_ENV

      - name: Publish to npm
        if: env.DEPLOY_PACKAGE == 'true'
        working-directory: ./npm
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
